application: appmator
version: sam
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /api/.+
  script: main.py
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)